"""Generate checked Python/C++ protocol definitions from robot_protocol.json."""
from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TYPES = {"B": "uint8_t", "H": "uint16_t", "h": "int16_t", "I": "uint32_t", "Q": "uint64_t"}
FLAGS = {"Reason", "Capability", "Validity", "HoldFlag"}


def outputs() -> dict[Path, str]:
    schema = json.loads((ROOT / "robot_protocol.json").read_text())
    py = ['"""Generated by generate_protocol.py; edit robot_protocol.json instead."""',
          "from enum import IntEnum, IntFlag", "import struct", "",
          f'VERSION = {schema["version"]}', f'MAX_PAYLOAD = {schema["max_payload"]}',
          f'FIRMWARE_MAX_CURRENT_MA = {schema["firmware_max_current_ma"]}',
          'SYNC = b"\\xa5\\x5a"', ""]
    cpp = ["// Generated by generate_protocol.py; edit robot_protocol.json instead.",
           "#pragma once", "#include <stdint.h>", "#include <stddef.h>",
           "namespace ProtocolV2 {", f'constexpr uint8_t VERSION = {schema["version"]};',
           f'constexpr uint8_t MAX_PAYLOAD = {schema["max_payload"]};',
           f'constexpr uint16_t FIRMWARE_MAX_CURRENT_MA = {schema["firmware_max_current_ma"]};']
    for name, entries in schema["enums"].items():
        py.append(f'class {name}({"IntFlag" if name in FLAGS else "IntEnum"}):')
        py.extend(f"    {key} = {value}" for key, value in entries.items())
        py.append("")
        cpp.append(f'enum class {name} : {"uint32_t" if name in FLAGS else "uint8_t"} {{')
        cpp.extend(f"  {key} = {value}," for key, value in entries.items())
        cpp.append("};")
    cpp.append("#pragma pack(push, 1)")
    for key, name in [("config", "Config"), ("status_header", "StatusHeader"), ("wheel", "WheelStatus")]:
        fields = schema[key]
        fmt = "<" + "".join(f["type"] for f in fields)
        tag = key.upper()
        py.extend([f"{tag}_FIELDS = {tuple(f['name'] for f in fields)!r}",
                   f"{tag}_FORMAT = {fmt!r}", f"{tag}_STRUCT = struct.Struct({tag}_FORMAT)"])
        offsets = {}
        offset = 0
        for f in fields:
            offsets[f["name"]] = offset
            offset += struct.calcsize("<" + f["type"])
        py.append(f"{tag}_OFFSETS = {offsets!r}")
        if key == "config":
            py.append(f"CONFIG_SPEC = {fields!r}")
        cpp.append(f"struct {name} {{")
        cpp.extend(f'  {TYPES[f["type"]]} {f["name"]};' for f in fields)
        cpp.extend(["};", f'static_assert(sizeof({name}) == {offset}, "{name} wire size");'])
        for f in fields:
            cpp.append(f'static_assert(offsetof({name}, {f["name"]}) == {offsets[f["name"]]}, "{name}.{f["name"]} offset");')
    cpp.extend(["struct Session { uint64_t boot_id; uint64_t host_session; };",
                "struct ConfigPayload { Session session; uint32_t config_id; Config config; };",
                "struct ArmPayload { Session session; uint32_t config_id; };",
                "struct TargetsPayload { Session session; int16_t target_centi_rpm[4]; uint8_t profile; };",
                "struct StatusPayload { StatusHeader header; WheelStatus wheels[4]; };",
                "#pragma pack(pop)",
                'static_assert(sizeof(ConfigPayload) == 98, "CONFIG size");',
                'static_assert(sizeof(ArmPayload) == 20, "ARM size");',
                'static_assert(sizeof(TargetsPayload) == 25, "TARGETS size");',
                'static_assert(sizeof(StatusPayload) == 182, "STATUS size");',
                "constexpr uint16_t STATUS_LENGTH = sizeof(StatusPayload);",
                "inline bool sequenceNewer(uint16_t candidate, uint16_t boundary) {",
                "  const uint16_t advance = uint16_t(candidate - boundary);",
                "  return advance > 0 && advance < 0x8000;", "}",
                "} // namespace ProtocolV2", ""])
    py.extend(["SESSION_STRUCT = struct.Struct('<QQ')", "CONFIG_PREFIX = struct.Struct('<QQI')",
               "ARM_STRUCT = CONFIG_PREFIX", "TARGETS_STRUCT = struct.Struct('<QQhhhhB')",
               "STATUS_LENGTH = STATUS_HEADER_STRUCT.size + 4 * WHEEL_STRUCT.size", ""])
    return {ROOT / "protocol_defs.py": "\n".join(py),
            ROOT / "hat_firmware/robot_hat/protocol_v2.h": "\n".join(cpp)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Stale protocol definitions: " + ", ".join(stale))


if __name__ == "__main__":
    main()
