// Generated by generate_protocol.py; edit robot_protocol.json instead.
#pragma once
#include <stdint.h>
#include <stddef.h>
namespace ProtocolV2 {
constexpr uint8_t VERSION = 2;
constexpr uint8_t MAX_PAYLOAD = 240;
constexpr uint16_t FIRMWARE_MAX_CURRENT_MA = 2700;
enum class FrameType : uint8_t {
  HELLO = 1,
  CONFIG = 2,
  ARM = 3,
  TARGETS = 4,
  STOP = 5,
  STATUS_REQ = 6,
  STATUS = 128,
};
enum class HatState : uint8_t {
  BOOT_STOPPING = 0,
  DISARMED = 1,
  ARMED = 2,
  FAULT = 3,
  SETTLING = 4,
  HOLDING = 5,
  STOPPING = 6,
};
enum class Profile : uint8_t {
  GENTLE = 0,
  NORMAL = 1,
  BOOST = 2,
};
enum class StopState : uint8_t {
  NONE = 0,
  REQUESTED = 1,
  IN_PROGRESS = 2,
  CONFIRMED = 3,
  UNCONFIRMED = 4,
};
enum class ConfigResult : uint8_t {
  NONE = 0,
  APPLIED = 1,
  REJECTED_STATE = 2,
  REJECTED_VALUE = 3,
  REJECTED_SESSION = 4,
};
enum class Reason : uint32_t {
  FIRMWARE_CEILING = 1,
  BOOST_EMPTY = 2,
  TEMP_STALE = 4,
  THERMAL_WARNING = 8,
  THERMAL_DERATE = 16,
  THERMAL_STOP = 32,
  FEEDBACK_STALE = 64,
  MOTOR_ERROR = 128,
  STALL_WARNING = 256,
  STALL = 512,
  ABNORMAL_CURRENT = 1024,
  COMMAND_TIMEOUT = 2048,
  HOLD_LIMITED = 4096,
  COOLDOWN = 8192,
  CONFIG_REJECTED = 16384,
  SESSION_MISMATCH = 32768,
  SPEED_ERROR = 65536,
  INSPECTION_REQUIRED = 131072,
};
enum class Capability : uint32_t {
  PROFILES = 1,
  SESSION = 2,
  HOLDING = 4,
  TEMPERATURE_AGE = 8,
  STOP_CONFIRMATION = 16,
  CONFIG_ID = 32,
  RESET_WATCHDOG = 64,
  POSITION = 128,
};
enum class Validity : uint32_t {
  RPM = 1,
  CURRENT = 2,
  POSITION = 4,
  TEMPERATURE = 8,
};
enum class HoldFlag : uint32_t {
  ACTIVE = 1,
  LIMITED = 2,
  DISARMED = 4,
};
enum class FaultCode : uint8_t {
  NONE = 0,
  COMMAND_TIMEOUT = 1,
  MOTOR_TIMEOUT = 2,
  BAD_MOTOR_FRAME = 3,
  MOTOR_FAULT = 4,
  OVERSPEED = 5,
  OVERTEMPERATURE = 6,
  STALL = 7,
  ABNORMAL_CURRENT = 8,
  CONFIGURATION_FAULT = 9,
  TEMPERATURE_STALE = 10,
  CONTROL_PROGRESS = 11,
};
#pragma pack(push, 1)
struct Config {
  uint16_t max_rpm;
  uint16_t max_current_ma;
  uint16_t neutral_brake_ma;
  uint16_t accel_rpm_s;
  uint16_t decel_rpm_s;
  uint16_t kp_ma_per_rpm;
  uint16_t ki_ma_per_rpm_s;
  uint16_t ff_ma_per_rpm_s;
  uint16_t watchdog_ms;
  uint16_t control_period_ms;
  uint16_t stall_time_ms;
  uint16_t gentle_current_ma;
  uint16_t normal_current_ma;
  uint16_t boost_current_ma;
  uint16_t boost_capacity_ms;
  uint16_t boost_refill_ms;
  uint16_t temp_poll_ms;
  uint16_t temp_boost_stale_ms;
  uint16_t temp_stop_stale_ms;
  uint16_t cooldown_ms;
  uint16_t cap_ramp_ma_s;
  uint16_t hold_current_ma;
  uint16_t hold_kp_ma_per_degree;
  uint16_t hold_ki_ma_per_degree_s;
  uint16_t hold_damping_ma_per_rpm;
  uint16_t neutral_settle_ms;
  uint16_t feedback_timeout_ms;
  uint16_t stall_target_centi_rpm;
  uint16_t stall_speed_centi_rpm;
  uint16_t stall_current_ma;
  uint16_t abnormal_current_ma;
  uint16_t abnormal_current_ms;
  uint16_t abnormal_margin_ma;
  uint16_t saturation_warn_ms;
  uint16_t stop_verify_ms;
  uint8_t temp_warn_c;
  uint8_t temp_derate_c;
  uint8_t temp_limit_c;
  uint8_t temp_release_c;
  uint8_t temp_hysteresis_c;
  uint8_t hold_enabled;
  uint8_t disarmed_hold_enabled;
  uint8_t stall_enabled;
  uint8_t hold_temp_c;
  uint32_t encoder_counts_per_rev;
};
static_assert(sizeof(Config) == 83, "Config wire size");
static_assert(offsetof(Config, max_rpm) == 0, "Config.max_rpm offset");
static_assert(offsetof(Config, max_current_ma) == 2, "Config.max_current_ma offset");
static_assert(offsetof(Config, neutral_brake_ma) == 4, "Config.neutral_brake_ma offset");
static_assert(offsetof(Config, accel_rpm_s) == 6, "Config.accel_rpm_s offset");
static_assert(offsetof(Config, decel_rpm_s) == 8, "Config.decel_rpm_s offset");
static_assert(offsetof(Config, kp_ma_per_rpm) == 10, "Config.kp_ma_per_rpm offset");
static_assert(offsetof(Config, ki_ma_per_rpm_s) == 12, "Config.ki_ma_per_rpm_s offset");
static_assert(offsetof(Config, ff_ma_per_rpm_s) == 14, "Config.ff_ma_per_rpm_s offset");
static_assert(offsetof(Config, watchdog_ms) == 16, "Config.watchdog_ms offset");
static_assert(offsetof(Config, control_period_ms) == 18, "Config.control_period_ms offset");
static_assert(offsetof(Config, stall_time_ms) == 20, "Config.stall_time_ms offset");
static_assert(offsetof(Config, gentle_current_ma) == 22, "Config.gentle_current_ma offset");
static_assert(offsetof(Config, normal_current_ma) == 24, "Config.normal_current_ma offset");
static_assert(offsetof(Config, boost_current_ma) == 26, "Config.boost_current_ma offset");
static_assert(offsetof(Config, boost_capacity_ms) == 28, "Config.boost_capacity_ms offset");
static_assert(offsetof(Config, boost_refill_ms) == 30, "Config.boost_refill_ms offset");
static_assert(offsetof(Config, temp_poll_ms) == 32, "Config.temp_poll_ms offset");
static_assert(offsetof(Config, temp_boost_stale_ms) == 34, "Config.temp_boost_stale_ms offset");
static_assert(offsetof(Config, temp_stop_stale_ms) == 36, "Config.temp_stop_stale_ms offset");
static_assert(offsetof(Config, cooldown_ms) == 38, "Config.cooldown_ms offset");
static_assert(offsetof(Config, cap_ramp_ma_s) == 40, "Config.cap_ramp_ma_s offset");
static_assert(offsetof(Config, hold_current_ma) == 42, "Config.hold_current_ma offset");
static_assert(offsetof(Config, hold_kp_ma_per_degree) == 44, "Config.hold_kp_ma_per_degree offset");
static_assert(offsetof(Config, hold_ki_ma_per_degree_s) == 46, "Config.hold_ki_ma_per_degree_s offset");
static_assert(offsetof(Config, hold_damping_ma_per_rpm) == 48, "Config.hold_damping_ma_per_rpm offset");
static_assert(offsetof(Config, neutral_settle_ms) == 50, "Config.neutral_settle_ms offset");
static_assert(offsetof(Config, feedback_timeout_ms) == 52, "Config.feedback_timeout_ms offset");
static_assert(offsetof(Config, stall_target_centi_rpm) == 54, "Config.stall_target_centi_rpm offset");
static_assert(offsetof(Config, stall_speed_centi_rpm) == 56, "Config.stall_speed_centi_rpm offset");
static_assert(offsetof(Config, stall_current_ma) == 58, "Config.stall_current_ma offset");
static_assert(offsetof(Config, abnormal_current_ma) == 60, "Config.abnormal_current_ma offset");
static_assert(offsetof(Config, abnormal_current_ms) == 62, "Config.abnormal_current_ms offset");
static_assert(offsetof(Config, abnormal_margin_ma) == 64, "Config.abnormal_margin_ma offset");
static_assert(offsetof(Config, saturation_warn_ms) == 66, "Config.saturation_warn_ms offset");
static_assert(offsetof(Config, stop_verify_ms) == 68, "Config.stop_verify_ms offset");
static_assert(offsetof(Config, temp_warn_c) == 70, "Config.temp_warn_c offset");
static_assert(offsetof(Config, temp_derate_c) == 71, "Config.temp_derate_c offset");
static_assert(offsetof(Config, temp_limit_c) == 72, "Config.temp_limit_c offset");
static_assert(offsetof(Config, temp_release_c) == 73, "Config.temp_release_c offset");
static_assert(offsetof(Config, temp_hysteresis_c) == 74, "Config.temp_hysteresis_c offset");
static_assert(offsetof(Config, hold_enabled) == 75, "Config.hold_enabled offset");
static_assert(offsetof(Config, disarmed_hold_enabled) == 76, "Config.disarmed_hold_enabled offset");
static_assert(offsetof(Config, stall_enabled) == 77, "Config.stall_enabled offset");
static_assert(offsetof(Config, hold_temp_c) == 78, "Config.hold_temp_c offset");
static_assert(offsetof(Config, encoder_counts_per_rev) == 79, "Config.encoder_counts_per_rev offset");
struct StatusHeader {
  uint64_t boot_id;
  uint64_t host_session;
  uint32_t capabilities;
  uint32_t build_id;
  uint32_t config_id;
  uint16_t accepted_seq;
  uint16_t applied_seq;
  uint32_t accepted_ms;
  uint32_t applied_ms;
  uint8_t state;
  uint8_t fault_code;
  uint8_t stop_state;
  uint8_t requested_profile;
  uint8_t applied_profile;
  uint8_t config_result;
  uint32_t reason_flags;
  uint32_t sweep_us;
  uint16_t command_age_ms;
  uint32_t boost_remaining_ms;
  uint32_t boost_capacity_ms;
  uint32_t boost_refill_remaining_ms;
  uint32_t cooldown_remaining_ms;
  uint8_t hold_flags;
  uint8_t fault_wheel;
  uint64_t hello_nonce;
  uint16_t config_ack_seq;
};
static_assert(sizeof(StatusHeader) == 84, "StatusHeader wire size");
static_assert(offsetof(StatusHeader, boot_id) == 0, "StatusHeader.boot_id offset");
static_assert(offsetof(StatusHeader, host_session) == 8, "StatusHeader.host_session offset");
static_assert(offsetof(StatusHeader, capabilities) == 16, "StatusHeader.capabilities offset");
static_assert(offsetof(StatusHeader, build_id) == 20, "StatusHeader.build_id offset");
static_assert(offsetof(StatusHeader, config_id) == 24, "StatusHeader.config_id offset");
static_assert(offsetof(StatusHeader, accepted_seq) == 28, "StatusHeader.accepted_seq offset");
static_assert(offsetof(StatusHeader, applied_seq) == 30, "StatusHeader.applied_seq offset");
static_assert(offsetof(StatusHeader, accepted_ms) == 32, "StatusHeader.accepted_ms offset");
static_assert(offsetof(StatusHeader, applied_ms) == 36, "StatusHeader.applied_ms offset");
static_assert(offsetof(StatusHeader, state) == 40, "StatusHeader.state offset");
static_assert(offsetof(StatusHeader, fault_code) == 41, "StatusHeader.fault_code offset");
static_assert(offsetof(StatusHeader, stop_state) == 42, "StatusHeader.stop_state offset");
static_assert(offsetof(StatusHeader, requested_profile) == 43, "StatusHeader.requested_profile offset");
static_assert(offsetof(StatusHeader, applied_profile) == 44, "StatusHeader.applied_profile offset");
static_assert(offsetof(StatusHeader, config_result) == 45, "StatusHeader.config_result offset");
static_assert(offsetof(StatusHeader, reason_flags) == 46, "StatusHeader.reason_flags offset");
static_assert(offsetof(StatusHeader, sweep_us) == 50, "StatusHeader.sweep_us offset");
static_assert(offsetof(StatusHeader, command_age_ms) == 54, "StatusHeader.command_age_ms offset");
static_assert(offsetof(StatusHeader, boost_remaining_ms) == 56, "StatusHeader.boost_remaining_ms offset");
static_assert(offsetof(StatusHeader, boost_capacity_ms) == 60, "StatusHeader.boost_capacity_ms offset");
static_assert(offsetof(StatusHeader, boost_refill_remaining_ms) == 64, "StatusHeader.boost_refill_remaining_ms offset");
static_assert(offsetof(StatusHeader, cooldown_remaining_ms) == 68, "StatusHeader.cooldown_remaining_ms offset");
static_assert(offsetof(StatusHeader, hold_flags) == 72, "StatusHeader.hold_flags offset");
static_assert(offsetof(StatusHeader, fault_wheel) == 73, "StatusHeader.fault_wheel offset");
static_assert(offsetof(StatusHeader, hello_nonce) == 74, "StatusHeader.hello_nonce offset");
static_assert(offsetof(StatusHeader, config_ack_seq) == 82, "StatusHeader.config_ack_seq offset");
struct WheelStatus {
  int16_t target_centi_rpm;
  int16_t rpm;
  int16_t current_ma;
  uint16_t position_raw;
  int16_t temp_c;
  uint16_t effective_cap_ma;
  uint16_t hold_cap_ma;
  uint16_t age_ms;
  uint16_t temp_age_ms;
  uint8_t error;
  uint8_t mode;
  uint8_t validity;
  uint32_t reason_flags;
};
static_assert(sizeof(WheelStatus) == 25, "WheelStatus wire size");
static_assert(offsetof(WheelStatus, target_centi_rpm) == 0, "WheelStatus.target_centi_rpm offset");
static_assert(offsetof(WheelStatus, rpm) == 2, "WheelStatus.rpm offset");
static_assert(offsetof(WheelStatus, current_ma) == 4, "WheelStatus.current_ma offset");
static_assert(offsetof(WheelStatus, position_raw) == 6, "WheelStatus.position_raw offset");
static_assert(offsetof(WheelStatus, temp_c) == 8, "WheelStatus.temp_c offset");
static_assert(offsetof(WheelStatus, effective_cap_ma) == 10, "WheelStatus.effective_cap_ma offset");
static_assert(offsetof(WheelStatus, hold_cap_ma) == 12, "WheelStatus.hold_cap_ma offset");
static_assert(offsetof(WheelStatus, age_ms) == 14, "WheelStatus.age_ms offset");
static_assert(offsetof(WheelStatus, temp_age_ms) == 16, "WheelStatus.temp_age_ms offset");
static_assert(offsetof(WheelStatus, error) == 18, "WheelStatus.error offset");
static_assert(offsetof(WheelStatus, mode) == 19, "WheelStatus.mode offset");
static_assert(offsetof(WheelStatus, validity) == 20, "WheelStatus.validity offset");
static_assert(offsetof(WheelStatus, reason_flags) == 21, "WheelStatus.reason_flags offset");
struct Session { uint64_t boot_id; uint64_t host_session; };
struct ConfigPayload { Session session; uint32_t config_id; Config config; };
struct ArmPayload { Session session; uint32_t config_id; };
struct TargetsPayload { Session session; int16_t target_centi_rpm[4]; uint8_t profile; };
struct StatusPayload { StatusHeader header; WheelStatus wheels[4]; };
#pragma pack(pop)
static_assert(sizeof(ConfigPayload) == 103, "CONFIG size");
static_assert(sizeof(ArmPayload) == 20, "ARM size");
static_assert(sizeof(TargetsPayload) == 25, "TARGETS size");
static_assert(sizeof(StatusPayload) == 184, "STATUS size");
constexpr uint16_t STATUS_LENGTH = sizeof(StatusPayload);
inline bool sequenceNewer(uint16_t candidate, uint16_t boundary) {
  const uint16_t advance = uint16_t(candidate - boundary);
  return advance > 0 && advance < 0x8000;
}
inline Config defaultConfig() {
  return Config{
    40, // max_rpm
    2700, // max_current_ma
    300, // neutral_brake_ma
    120, // accel_rpm_s
    180, // decel_rpm_s
    20, // kp_ma_per_rpm
    4, // ki_ma_per_rpm_s
    0, // ff_ma_per_rpm_s
    300, // watchdog_ms
    15, // control_period_ms
    1000, // stall_time_ms
    800, // gentle_current_ma
    1500, // normal_current_ma
    2500, // boost_current_ma
    20000, // boost_capacity_ms
    60000, // boost_refill_ms
    500, // temp_poll_ms
    750, // temp_boost_stale_ms
    1500, // temp_stop_stale_ms
    3000, // cooldown_ms
    1000, // cap_ramp_ma_s
    300, // hold_current_ma
    2, // hold_kp_ma_per_degree
    1, // hold_ki_ma_per_degree_s
    20, // hold_damping_ma_per_rpm
    300, // neutral_settle_ms
    150, // feedback_timeout_ms
    800, // stall_target_centi_rpm
    200, // stall_speed_centi_rpm
    250, // stall_current_ma
    2700, // abnormal_current_ma
    200, // abnormal_current_ms
    400, // abnormal_margin_ma
    500, // saturation_warn_ms
    1500, // stop_verify_ms
    50, // temp_warn_c
    55, // temp_derate_c
    65, // temp_limit_c
    45, // temp_release_c
    3, // temp_hysteresis_c
    1, // hold_enabled
    0, // disarmed_hold_enabled
    1, // stall_enabled
    55, // hold_temp_c
    32768, // encoder_counts_per_rev
  };
}
inline bool validConfig(const Config &c) {
  if (c.max_rpm < 1 || c.max_rpm > 200) return false;
  if (c.max_current_ma < 1 || c.max_current_ma > 2700) return false;
  if (c.neutral_brake_ma < 0 || c.neutral_brake_ma > 2700) return false;
  if (c.accel_rpm_s < 1 || c.accel_rpm_s > 5000) return false;
  if (c.decel_rpm_s < 1 || c.decel_rpm_s > 5000) return false;
  if (c.kp_ma_per_rpm < 0 || c.kp_ma_per_rpm > 1000) return false;
  if (c.ki_ma_per_rpm_s < 0 || c.ki_ma_per_rpm_s > 1000) return false;
  if (c.ff_ma_per_rpm_s < 0 || c.ff_ma_per_rpm_s > 1000) return false;
  if (c.watchdog_ms < 100 || c.watchdog_ms > 1000) return false;
  if (c.control_period_ms < 10 || c.control_period_ms > 100) return false;
  if (c.stall_time_ms < 100 || c.stall_time_ms > 5000) return false;
  if (c.gentle_current_ma < 1 || c.gentle_current_ma > 2700) return false;
  if (c.normal_current_ma < 1 || c.normal_current_ma > 2700) return false;
  if (c.boost_current_ma < 1 || c.boost_current_ma > 2700) return false;
  if (c.boost_capacity_ms < 1000 || c.boost_capacity_ms > 20000) return false;
  if (c.boost_refill_ms < 60000 || c.boost_refill_ms > 65535) return false;
  if (c.temp_poll_ms < 100 || c.temp_poll_ms > 500) return false;
  if (c.temp_boost_stale_ms < 100 || c.temp_boost_stale_ms > 750) return false;
  if (c.temp_stop_stale_ms < 200 || c.temp_stop_stale_ms > 1500) return false;
  if (c.cooldown_ms < 1000 || c.cooldown_ms > 60000) return false;
  if (c.cap_ramp_ma_s < 1 || c.cap_ramp_ma_s > 10000) return false;
  if (c.hold_current_ma < 0 || c.hold_current_ma > 2700) return false;
  if (c.hold_kp_ma_per_degree < 0 || c.hold_kp_ma_per_degree > 1000) return false;
  if (c.hold_ki_ma_per_degree_s < 0 || c.hold_ki_ma_per_degree_s > 1000) return false;
  if (c.hold_damping_ma_per_rpm < 0 || c.hold_damping_ma_per_rpm > 1000) return false;
  if (c.neutral_settle_ms < 100 || c.neutral_settle_ms > 5000) return false;
  if (c.feedback_timeout_ms < 100 || c.feedback_timeout_ms > 250) return false;
  if (c.stall_target_centi_rpm < 100 || c.stall_target_centi_rpm > 20000) return false;
  if (c.stall_speed_centi_rpm < 0 || c.stall_speed_centi_rpm > 20000) return false;
  if (c.stall_current_ma < 1 || c.stall_current_ma > 2700) return false;
  if (c.abnormal_current_ma < 1 || c.abnormal_current_ma > 2700) return false;
  if (c.abnormal_current_ms < 50 || c.abnormal_current_ms > 2000) return false;
  if (c.abnormal_margin_ma < 0 || c.abnormal_margin_ma > 1000) return false;
  if (c.saturation_warn_ms < 100 || c.saturation_warn_ms > 5000) return false;
  if (c.stop_verify_ms < 100 || c.stop_verify_ms > 5000) return false;
  if (c.temp_warn_c < 30 || c.temp_warn_c > 60) return false;
  if (c.temp_derate_c < 30 || c.temp_derate_c > 65) return false;
  if (c.temp_limit_c < 40 || c.temp_limit_c > 70) return false;
  if (c.temp_release_c < 20 || c.temp_release_c > 60) return false;
  if (c.temp_hysteresis_c < 1 || c.temp_hysteresis_c > 10) return false;
  if (c.hold_enabled < 0 || c.hold_enabled > 1) return false;
  if (c.disarmed_hold_enabled < 0 || c.disarmed_hold_enabled > 1) return false;
  if (c.stall_enabled < 0 || c.stall_enabled > 1) return false;
  if (c.hold_temp_c < 30 || c.hold_temp_c > 65) return false;
  if (c.encoder_counts_per_rev < 256 || c.encoder_counts_per_rev > 65536) return false;
  if (!(c.gentle_current_ma <= c.normal_current_ma && c.normal_current_ma <= c.boost_current_ma)) return false;
  if (!(c.neutral_brake_ma <= c.max_current_ma && c.hold_current_ma <= c.max_current_ma)) return false;
  if (!(c.temp_release_c < c.temp_warn_c && c.temp_warn_c < c.temp_derate_c && c.temp_derate_c < c.temp_limit_c)) return false;
  if (!(c.temp_release_c + c.temp_hysteresis_c < c.temp_derate_c)) return false;
  if (!(c.temp_poll_ms < c.temp_boost_stale_ms && c.temp_boost_stale_ms < c.temp_stop_stale_ms)) return false;
  if (!(c.boost_refill_ms >= c.boost_capacity_ms)) return false;
  if (!(c.stall_speed_centi_rpm < c.stall_target_centi_rpm)) return false;
  if (!(c.control_period_ms < c.feedback_timeout_ms && c.feedback_timeout_ms < c.watchdog_ms)) return false;
  if (!(!c.disarmed_hold_enabled || c.hold_enabled)) return false;
  if (!(c.temp_release_c < c.hold_temp_c && c.hold_temp_c <= c.temp_limit_c)) return false;
  return true;
}
} // namespace ProtocolV2
