#!/usr/bin/env python3
"""Generate/check firmware build identity from every compiled local source."""
from pathlib import Path
import argparse
import hashlib
root=Path(__file__).resolve().parent/'robot_hat'
parts=[]
for path in sorted(root.iterdir()):
    if path.suffix in ('.h','.ino','.cpp') and path.name!='build_identity.h':
        parts.append(path.name.encode()+b'\0'+path.read_bytes()+b'\0')
digest=hashlib.sha256(b''.join(parts)).hexdigest()
text=f'// Generated by hat_firmware/generate_build_identity.py\n#pragma once\n#define ROBOT_BUILD_ID 0x{digest[:8]}U\n#define ROBOT_BUILD_SHA256 "{digest}"\n'
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
output=root/'build_identity.h'
if args.check:
    if not output.exists() or output.read_text()!=text:raise SystemExit('Firmware build identity is stale; regenerate before compiling.')
else:output.write_text(text)
print(digest)
